spring:
  application:
    name: pigeon

  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/pigeon
    username: postgres
    password: 200361816
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Options: validate, update, create, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        id.new_generator_mappings: true

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate: INFO
