spring:
  application:
    name: racetrack

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: PegieonRacer

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver: INFO
